### ISSUE TITLE
Scrubbing the history of .yarn

### ISSUE THREAD

**Issue by yacinehmito** [solidui/solid-playground#13]
I just cloned the repository, and it took a while because it weighs close to 300MB.
I realise that this is due to yarn v2 zero-installs. The tradeoff is that, for a larger repo, we don't waste time installing dependencies.
However, since the switch to pnpm, we are now getting the downside of yarn v2 zero-installs without the upside.

Would you be keen on scrubbing the git history for the `.yarn` folder in order to reduce the size of the repository?
This is likely to affect the whole history and will require a `push --force`, so currently cloned repositories won't mesh well.
However, if this is to be done at some point, then the earlier the better.

I can provide a script to perform the operation if you welcome it.

**Comment by amoutonbrady** [comment]
Ah this is the reason why...

I was wondering why it'd still takes a bazillion years even with the move to pnpm.

Thanks. I'll look into it as soon as possible!

**Comment by yacinehmito** [comment]
Here's the script:

```bash
#!/usr/bin/env bash

set -e

DIR="$(pwd)/solid-playground-no-yarn"

function run() {
  if ! command -v git-filter-repo &>/dev/null; then
    # This assumes you are on macOS with Homebrew installed.
    # If not, see https://github.com/newren/git-filter-repo/blob/main/INSTALL.md
    echo "Installing git-filter-repo with Homebrew."
    brew install git-filter-repo
  fi

  git clone git@github.com:solidui/solid-playground.git $DIR
  cd $DIR

  git filter-repo --path .yarn/cache/ --invert-paths
  git gc

  read -p "Force push to master now? (Y/n) " -n 1 -r
  if [[ $REPLY =~ ^[Yy]?$ ]]; then
    git push --force origin master
  fi
}

echo "This script will clone solidui/solid-playground in $DIR."
echo "Then, it will remove the yarn cache from the git history."
echo "Local copies of the repository, on all machines, should stop being used."
read -p "Proceed? (Y/n) " -n 1 -r
echo # (optional) move to a new line
if [[ $REPLY =~ ^[Yy]?$ ]]; then
  run
else
  echo "Aborted."
  exit 1
fi
```

**Comment by yacinehmito** [comment]
I tested it on my fork. The repo is down to <10MB.

![image](https://user-images.githubusercontent.com/6893840/117221994-b2f15b00-ae0a-11eb-834a-c48092c8ef00.png)

**Comment by amoutonbrady** [comment]
It did something a little funky where I had to reset the remote origin but besides that it worked like a charm! Thank you very much for the detailed script.
